use_frameworks!
target 'IDCardDetector_Example' do
    pod 'IDCardDetector', :path => '../'
    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'IQKeyboardManagerSwift'
    pod 'NVActivityIndicatorView'
    pod 'FaceCropper'
target 'IDCardDetector_Tests' do
  inherit! :search_paths
  
end
end
